### ISSUE TITLE
Build pkgdown on build

### ISSUE THREAD

**Issue by MarkEdmondson1234** [MarkEdmondson1234/googleCloudRunner#14]
working :D generalise this cloudbuild.yaml via `cr_buildstep_git()` and perhaps a `cr_deploy_pkgdown()` 

reference:

* https://cloud.google.com/cloud-build/docs/access-private-github-repos
* https://github.com/GoogleCloudPlatform/gke-gitops-tutorial-cloudbuild/blob/master/cloudbuild-delivery.yaml
```yaml
options:
  env:
  - 'CR_REGION=$_REGION'
  - 'GCE_DEFAULT_PROJECT_ID=$PROJECT_ID'
  - 'CR_BUILD_EMAIL=$_BUILD_EMAIL'
  - 'GCS_DEFAULT_BUCKET=$_BUCKET'
steps:
- name: 'gcr.io/cloud-builders/gcloud'
  id: decrypt gitkey
  args:
  - kms
  - decrypt
  - --ciphertext-file=cb_rsa.enc
  - --plaintext-file=/root/.ssh/id_rsa
  - --location=global
  - --keyring=my-keyring
  - --key=github-key
  volumes:
  - name: 'ssh'
    path: /root/.ssh
# Set up git with key and domain
- name: 'gcr.io/cloud-builders/git'
  id: setup gitkey
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    chmod 600 /root/.ssh/id_rsa
    cat <<EOF >/root/.ssh/config
    Hostname github.com
    IdentityFile /root/.ssh/id_rsa
    EOF
    cp inst/ssh/known_hosts /root/.ssh/known_hosts
    git config --global user.name "googleCloudRunner"
    git config --global user.email $_BUILD_EMAIL
  volumes:
  - name: 'ssh'
    path: /root/.ssh
- name: 'gcr.io/cloud-builders/git'
  id: clone under new git creds
  args:
  - clone
  - git@github.com:$_GITHUB_REPO
  volumes:
  - name: 'ssh'
    path: /root/.ssh
- name: 'gcr.io/gcer-public/packagetools:master'
  id: Build website
  dir: googleCloudRunner
  args:
  - "Rscript"
  - "-e"
  - |
    devtools::install()
    list.files()
    pkgdown::build_site()
# Push build - remember to restrict other builds away from /docs
# otherwise it will trigger again in never ending git commit loop
- name: 'gcr.io/cloud-builders/git'
  id: push website
  dir: googleCloudRunner
  entrypoint: 'bash'
  args:
  - '-c'
  - |
    git add . && \
    git commit -a -m "Build website from commit ${COMMIT_SHA}: \
                      $(date +"%Y-%m-%d_%H-%M-%S")" && \
    git push git@github.com:$_GITHUB_REPO
  volumes:
  - name: 'ssh'
    path: /root/.ssh
```
