### ISSUE TITLE
artifacts don't render cloud build yaml correctly

### ISSUE THREAD

**Issue by MarkEdmondson1234** [MarkEdmondson1234/googleCloudRunner#28]
> failed unmarshalling build config inst/cloudbuild/cloudbuild_rmd.yml: json: cannot unmarshal array into Go value of type string

https://console.cloud.google.com/cloud-build/builds/6c856a1b-0595-4f1b-a4f1-febd71b75c89?project=mark-edmondson-gde

fails:

```yaml
steps:
- name: gcr.io/gcer-public/render_rmd:master
  args:
  - Rscript
  - -e
  - rmarkdown::render('scheduled_rmarkdown.Rmd', output_file = 'scheduled_rmarkdown.html')
  id: render rmd
  dir: inst/scheduled_rmarkdown/
artifacts:
  objects:
    location:
    - gs://mark-edmondson-public-read
    paths:
    - inst/scheduled_rmarkdown/scheduled_rmarkdown.html
```

works:

```yaml
...
artifacts:
  objects:
    location: 'gs://mark-edmondson-public-read'
    paths: ['inst/scheduled_rmarkdown/scheduled_rmarkdown.html']
```

`cr_build_yaml_artifiact()` does not render correctly

```r
rmd_build <- cr_build_yaml(
  steps = cr_buildstep_r(
      id="render rmd",
      r = r,
      name = "gcr.io/gcer-public/render_rmd:master",
      dir = "inst/scheduled_rmarkdown/"
    ),
  artifacts = cr_build_yaml_artifact(
                 "inst/scheduled_rmarkdown/scheduled_rmarkdown.html", 
                 bucket = "mark-edmondson-public-read")
  )
```
