### ISSUE TITLE
How to use auth secrets on Cloud Build

### ISSUE THREAD

**Issue by MarkEdmondson1234** [MarkEdmondson1234/googleCloudRunner#3]
It seems `googleAuthR::gar_gce_auth()` doesn't work out of the box :( on cloud build, so implement service keys upload via encrypted services 

https://cloud.google.com/cloud-build/docs/securing-builds/use-encrypted-secrets-credentials

```yaml
steps:
- name: gcr.io/cloud-builders/gcloud
  args:
  - kms
  - decrypt
  - --ciphertext-file=secrets.json.enc
  - --plaintext-file=secrets.json
  - --location=global
  - --keyring=[KEYRING-NAME]
  - --key=[KEY-NAME]
# more steps here
```
